#!/usr/bin/env ruby
# script/roster_listener

ENV['RAILS_ENV'] ||= 'production'

require  File.expand_path('../../config/environment',  __FILE__)

puts "Starting master tree roster listener"
Roster.subscribe