#!/usr/bin/env ruby
# script/roster_listener

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require APP_PATH

Rails.application.require_environment!

puts "Starting master tree roster listener"
Roster.subscribe