# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{taxamatch_rb}
  s.version = "0.7.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dmitry Mozzherin"]
  s.date = %q{2011-06-23}
  s.description = %q{This gem implements algorithm for fuzzy matching scientific names developed by Tony Rees}
  s.email = %q{dmozzherin@eol.org}
  s.extensions = ["ext/damerau_levenshtein/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "Makefile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/damerau_levenshtein/damerau_levenshtein.c",
    "lib/taxamatch_rb.rb",
    "lib/taxamatch_rb/atomizer.rb",
    "lib/taxamatch_rb/authmatch.rb",
    "lib/taxamatch_rb/damerau_levenshtein_mod.rb",
    "lib/taxamatch_rb/normalizer.rb",
    "lib/taxamatch_rb/phonetizer.rb",
    "spec/damerau_levenshtein_mod_test.txt",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/taxamatch_rb_spec.rb",
    "spec/taxamatch_test.txt",
    "taxamatch_rb.gemspec"
  ]
  s.homepage = %q{http://github.com/GlobalNamesArchitecture/taxamatch_rb}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Implementation of Tony Rees Taxamatch algorithms}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<biodiversity>, ["~> 0.5.13"])
      s.add_runtime_dependency(%q<biodiversity19>, ["~> 0.5.13"])
      s.add_runtime_dependency(%q<rake-compiler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<ruby-prof>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_runtime_dependency(%q<biodiversity>, [">= 0.5.13"])
    else
      s.add_dependency(%q<biodiversity>, ["~> 0.5.13"])
      s.add_dependency(%q<biodiversity19>, ["~> 0.5.13"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<ruby-prof>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<biodiversity>, [">= 0.5.13"])
    end
  else
    s.add_dependency(%q<biodiversity>, ["~> 0.5.13"])
    s.add_dependency(%q<biodiversity19>, ["~> 0.5.13"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<ruby-prof>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<biodiversity>, [">= 0.5.13"])
  end
end

